default:
  verification:
    try: 5
  web:
    title: 'Tipi: Travel Experiences Shared'
    description: 'Tipi helps you meet new people & share tips while you travel. And discover nearby travel experiences in all countries.'
    keywords: 'travel,backpacker,travel,top 10 things,hotel,hostel,places'
  mobile:
    rating:
      - 
        day: 3
        launch: 8
      - 
        day: 5
        launch: 14
      - 
        day: 7
        launch: 20
      - 
        day: 9
        launch: 26
      - 
        day: 12
        launch: 30
  cars:
    suggestions:
      description:
        - "این make model با شتاب acceleration و cylinder سیلندر و ماکزیمم سرعت speed  به عنوان  یک ماشین style بسیار مناسب شماست. امکانات این ماشین شیشه window - ایربگ airbag - ترمز brake و extra میباشد. این ماشین دیفرانسیل differential با حجم باک capacity می باشد."
        - "make model یک ماشین بسیار خوب style میباشد. اگر به دنبال سرعت speed  و شتاب acceleration و ماشین cylinder سیلندری هستید make برای شما مناسب است. تجهیزات این ماشین : شیشه window - ایربگ airbag - ترمز brake و extra . ماشین make model جزو ماشینهای دیفرانسیل differential با حجم باک capacity می باشد."
    search:
      size: 10
  colors: 
    primaries: [18, 19, 31, 37, 9, 11, 23, 6]
    list:
      - آبی
      - آلبالویی
      - اخرائی
      - اطلسی
      - بادمجانی
      - برنز
      - بژ
      - بنفش
      - پوست پیازی
      - خاکستری
      - خاکی
      - دلفینی
      - زرد
      - زرشکی
      - زیتونی
      - سبز
      - سربی
      - سرمه ای
      - سفید
      - سفید صدفی
      - شتری
      - صورتی
      - طلائی
      - طوسی
      - عدسی
      - عنابی
      - قرمز
      - قهوه ای
      - گیلاسی
      - مارون
      - مسی
      - مشکی
      - موکا
      - نارنجی
      - نامشخص
      - نقرآبی
      - نقره ای
      - نوک مدادی
      - کربن بلک
      - کرم
      - یاسی
      - یشمی
